-- Auto-generated from schema-map-postgres.yaml (map@sha1:621FDD3D99B768B6A8AD92061FB029414184F4B3)
-- engine: postgres
-- table:  vat_validations

CREATE TABLE IF NOT EXISTS vat_validations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vat_id VARCHAR(50) NOT NULL,
  country_iso2 CHAR(2) NOT NULL,
  valid BOOLEAN NOT NULL,
  checked_at TIMESTAMPTZ(6) NOT NULL,
  raw JSONB NULL
);
